### ISSUE TITLE
Examples of issue tickets and efficiency benefits of working open?

### ISSUE THREAD

**Issue by ewallace** [swinterbourne/riboviz-work#4] opened 2021-09-10 14:25 UTC
We could strengthen the draft on efficiency benefits of working together, for example
* weren't familiar with issue tickets
* was scary at first, then it was efficient
* learn to ask others for help (e.g. Alex Cope branch)
* run into same problems again, if it wasn't documented... (e.g. Weinberg dataset)

**Comment by 3mma-mack** [comment] 2021-09-10 15:43
I have added the sentence `This development is clearer now that we occasionally return to issue tickets written in the early stages of the project, and curse at our past selves for documenting the problem, and more importantly the solution, so poorly. ` to partially address the `run into same problems again` point.

**Comment by ewallace** [comment] 2021-09-12 12:02
I like this addition. Is there a _specific_ example issue we could mention though?

In my PI perspective I put in some specific examples of building up to adding new datasets (see draft #10). That often helps to illustrate the more general point.

**Comment by ewallace** [comment] 2021-09-28 13:19
@swinterbourne has mentioned one example, will check it's in (or not) and then close this issue.

**Comment by swinterbourne** [comment] 2021-09-28 15:05
There is a paragraph under the **What was good or bad section** that addresses this:

Our communication skills were greatly improved by interacting with our supervisors and the lab group in the course of the project through our Stand-Up Reports and issue tickets on GitHub. The importance of communicating progress and obstacles frequently in a precise and informative manner, especially as all communication occurred virtually, quickly became obvious to avoid confusion and get help more quickly. (***) This development is clearer now that we occasionally return to issue tickets written in the early stages of the project, and curse at our past selves for documenting the problem, and more importantly the solution, so poorly.

Could this be improved by adding more detail in this (***) section? Or leave as is?

- For example, a prolonged delay was caused by a failed dataset run which could have been avoided if the issue ticket had been updated and detailed sufficiently.

or

- Experiences such as not updating and detailing issue tickets sufficiently which resulted in avoidable delays serve as reminders.

**Comment by FlicAnderson** [comment] 2021-09-28 16:19
@swinterbourne - @3mma-mack and I agree with adding this option: 

> Could this be improved by adding more detail in this (***) section? Or leave as is?
> 
> For example, a prolonged delay was caused by a failed dataset run which could have been avoided if the issue ticket had been updated and detailed sufficiently.

**Comment by swinterbourne** [comment] 2021-09-28 16:27
I added the suggested sentence to the paragraph and merged it. This should be good to close now.

**Closed by swinterbourne** 2021-09-28 16:27 UTC
